// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=ts"
// @generated from file generation.proto (package gooseai, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {Answer, ChainRequest, Request} from "./generation_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 *
 * gRPC services
 *
 *
 * @generated from service gooseai.GenerationService
 */
export const GenerationService = {
  typeName: "gooseai.GenerationService",
  methods: {
    /**
     * @generated from rpc gooseai.GenerationService.Generate
     */
    generate: {
      name: "Generate",
      I: Request,
      O: Answer,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc gooseai.GenerationService.ChainGenerate
     */
    chainGenerate: {
      name: "ChainGenerate",
      I: ChainRequest,
      O: Answer,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

